### ISSUE TITLE
invalid_request, can't post parameters

### ISSUE THREAD

**Issue by enisgur** [mrsarm/reqclient#10]
I need help to get my access_token. it had been a week but still could't find out how, and decide to request help from here.
I am trying to request post to oauth.opskins but it doesn't see my parametes. How can I send required parameters to server?

```
var client = new RequestClient({
            baseUrl:"https://oauth.opskins.com/v1/",
            debugRequest:true, debugResponse:true,
            auth:{
                user: '**my_client_id_here**',
                pass: '**my_secret_here**'
            }
        });
    
        var resp = client.post("access_token", {"grant_type": "authorization_code", "code":`${req.query.code}`},{headers: {"authorization":"Basic **my_key-here**"}});

```

I am getting this output

`[Response   access_token]<- Status 400 - {"error":"invalid_request","error_description":"The grant_type parameter is required"}`

**Comment by mrsarm** [comment]
Hi @enisgur ,

If you are trying to access to a protected service with OAuth2, you shouldn't need to make the request manually, you only need to setup properly the Oauth2 settings, and before try to access to any endpoint in your secured service, reqclient will try to authenticate first. Take a look a the Twitter example [here](https://github.com/mrsarm/reqclient#twitter-example),where the intend is to try to access to the "trends/place.json" endpoint, but because `RequestClient` object was created with the `oauth2` settings, the library try first to get the token using those settings against the OAuth2 endpoint.

But taking one more look to your example, you are trying to send also an "authorization" header, with a "Basic" token, so I not sure what is your intend.

But here are some observations:
- When you use the `auth` setting in the constructor, you are using [HTTP Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side), that it's translated to a "authorization" header automatically, but you are also sending an "authorization" header in the request, so one is overwriting the other. The `auth` object it's just a convenient way to encode the string that the Basic method requires.
- Because you are trying to access directly to the authentication endpoint, not using the OAuth2 facilities the library has, you need to follow all the OAuth2 guidelines to connect with the server (despite maybe the server implementation has some differences with the spec). One of this rules is that you need to send the body parameters in the POST request encoded as form data, not JSON (default), so you need to add in the 3er parameter or at the `RequestClient` constructor the option `contentType: "formData"`. That is the reason because the server is responding _The grant_type parameter is required_ despite you are sending it (but with the wrong encoding),

**Comment by mrsarm** [comment]
Hey @enisgur ,

Did you solve the issue?

**Comment by enisgur** [comment]
thank you for your help. Yes I solve the issue. Thanks again
