### ISSUE TITLE
curl response cannot be tapped

### ISSUE THREAD

**Issue by deepakkbc** [mrsarm/reqclient#9]
Hello,
I have following code:
 var RequestClient = require("reqclient").RequestClient;
    var client = new RequestClient({
        baseUrl:"http://19.160.168.50:3000/api",
        debugRequest:false, debugResponse:true
    });
    var jsData = { "$class": "org.acme.test.User",
        "user_id": "u6","user_oro_id": "rag",
        "firstname": "raghav","lastname": "bhatta",
        "email": "rag@gmail.com", "Phone": "123",
        "address": "adasd",  "address1": "asda",
        "city":"ada", "state": "asd", "country": "dfd",
        "user_type": "dfd"
    };
    let resp = client.post("User", jsData, {headers: {"Content-Type":"application/json", "Accept":"application/json"}});
But I cannot tapped response. I want to read statusCode from the response which is not happening. Can you please suggest.

Thank you

**Comment by mrsarm** [comment]
Hi @deepakkbc,

I'm not sure about the issue, are you aware that the object `resp` in the `let resp = client.po...` statement is a Promise object? You need to get the response once the promise is resolved, check the README of the project with some examples of how to get the response from a `.then(...` chaining, or using *async/await*, but in both cases, dealing with promise is not as easy as looks like, you should take some extra reads to undestand well how promises and async programming works.

But if you are aware of that and the example provided is just an extract of the whole code, yes, it wont give you the `statusCode` in that way (but there is a way below), but default reqclient only returns the response body, and if it's a JSON response, it will unserialize it to give you the response as a JS object to be easily managed.

The library do this because most of the time you don't need the status code, becuase if something fails and the status code is not between 200-299, it will return promise that it would rejects, so you will put your code to treat failures in the `catch()` block, or `...catch {}...` if you are using async / await syntax.

That said, some time is need to catch the status code to get a more granular idea of what kind of success or failure we are dealing with, in these cases, you need to pass the option `fullResponse: true` to get the all response object. You can set this option in the client creation if you want this behaviour for all the requests in your project, in your example it would be like this:

```js
var client = new RequestClient({
  baseUrl:"http://19.160.168.50:3000/api",
  debugRequest:false, debugResponse:true,
  fullResponse: true
});
```

Or you can pass to only some requests and let the default behaviour for the rest of the requests:

```js
 let resp = client.post("User", jsData, {fullResponse: true, headers: {"Content-Type":"application/json", "Accept":"application/json"}});
```

Then in both cases you can check the status code and get the response body like this (example extracted from the [README](https://github.com/mrsarm/reqclient#override-options) page):

```js
resp.then(httpResponse => {
  if (httpResponse.statusCode == 201) {
    // Registry created, do something with httpResponse.body ...
  } else if (httpResponse.statusCode == 200) {
    // Registry updated, do something with httpResponse.body ...
  } else {
    // Do something
  }
});
```

**Comment by deepakkbc** [comment]
Thank you for your reply.I was missing fullResponse: true
, now it works. thanks
